dist: trusty
language: rust
services: docker
sudo: required
cache: cargo
os:
  - linux
  - osx
rust:
  - stable
  - nightly
matrix:
  allow_failures:
    - rust: nightly
branches:
  only:
    - master
    - develop
script:
  - cargo build --release
  # - cargo deb
  - cargo doc

before_deploy: ./deploy.sh
deploy:
  provider: releases
  api_key:
    secure: zuOwBXefkVKPzw49bZ3BSMGDn2gfWslXlvnoQD8Lr2DJ7Vq1BoUz19KOaD+wOzFEUgSa/fX8zrs0+LlhSxvWhsPJsxE3FN1JWspplkmgWbUG0xpMdtCyMivvUvJuzF/GNlHnrjfpAJOA8UnkyMwKGTe1HkQYM2AOFGXSwwu1jXp62ZIB9ZjyNpkHIUuonw2IkKiE06mfXPApxvNMoIFfWEbNAXBev/c0greVc77pigRgyMiROVBRjY8H6isgXLrxaYBP7YVeK+1k/H2yTR8DbOKmgCSbE8FLDxJO89pG+E1UxnMY1CNq09WB9GON6kQlL8eHCuRxnCRJSyP9OIfmJQGdvC+nFfk0m1kbsHZ5DjQOf5ClKrY3fXYhkXOBKs4iHzKegWyoci27o/Z6ZGc0gGdWfREabRfVSdIGtGD9a6GhhlGv31WiF2mDYWV8Y5xM3wLjaw0ogseCjMqUNwxDe9FxRDxmEovRZmgP0JJAdaRrN3+U9qA6qtB674ZwaVV6m2RrpEqKYk5tXuibZqcRRY6pN3uppEZgDxpOzMJl/n4M910tEZlXw5UUco5flcFvH7ljZoqI7cFNFiIikGHVfuaNQkP+hwWsCAH42NzOwgSgYNd20zeXgHQdxkM97ILDWiz7PsTPsgosxjLglLSn3iJZ7YpqHh4ygMX6OfTMHG0=
  file: 
   - target/release/fool
   - target/debian/*.deb
  on:
    repo: spacekookie/fool
    tags: true
    branch: master

notifications:
  email:
    on_success: never
    on_failure: never
