[package]
name = "fool"
description = "A powerful and simple to use git client for Terminal interfaces"
version = "0.1.0"
authors = ["Katharina Fey <kookie@spacekookie.de>"]

[dependencies]
ncurses = "5.88.0"