# Every field in a theme file is optional.

shadow = false
borders = "outset" # Alternatives are "none" and "simple"

# Base colors are red, green, blue, cyan, magenta, yellow, white and black.
[colors]
	# There are 3 ways to select a color:
	# - The 16 base colors are selected by name:
	#       "blue", "light red", "magenta", ...
	# - Low-resolution colors use 3 characters, each <= 5:
	#       "541", "003", ...
	# - Full-resolution colors start with '#' and can be 3 or 6 hex digits:
	#       "#1A6", "#123456", ...

	# If the value is an array, the first valid
	# and supported color will be used.
	background = ["#333333", "454", "magenta"]

	# If the terminal doesn't support custom color (like the linux TTY),
	# non-base colors will be skipped.
	shadow     = ["#333333", "blue"]
	view       = "#CCC"

	# An array with a single value has the same effect as a simple value.
	primary   = "#3333FF"
	secondary = "#333"
	tertiary  = "#6666FF"

	# Hex values can use lower or uppercase.
	# (base color MUST be lowercase)
	title_primary   = ["BLUE", "yellow"] # `BLUE` will be skipped.
	title_secondary = "#FFF"

	# Lower precision values can use only 3 digits.
	highlight          = "#FFF"
	highlight_inactive = "#FFF"


